/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedNewUniverseRouteImport } from './routes/_authenticated.new-universe'
import { Route as AuthenticatedUniverseIdRouteImport } from './routes/_authenticated.universe.$id'
import { Route as AuthenticatedUniverseIdIndexRouteImport } from './routes/_authenticated.universe.$id.index'
import { Route as AuthenticatedUniverseIdChaptersRouteImport } from './routes/_authenticated.universe.$id.chapters'
import { Route as AuthenticatedUniverseIdCharactersRouteImport } from './routes/_authenticated.universe.$id.characters'
import { Route as AuthenticatedUniverseIdContinuityRouteImport } from './routes/_authenticated.universe.$id.continuity'
import { Route as AuthenticatedUniverseIdDnaRouteImport } from './routes/_authenticated.universe.$id.dna'
import { Route as AuthenticatedUniverseIdMemoryRouteImport } from './routes/_authenticated.universe.$id.memory'
import { Route as AuthenticatedUniverseIdTimelineRouteImport } from './routes/_authenticated.universe.$id.timeline'
import { Route as AuthenticatedUniverseIdVersionsRouteImport } from './routes/_authenticated.universe.$id.versions'
import { Route as AuthenticatedUniverseIdWorldRouteImport } from './routes/_authenticated.universe.$id.world'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewUniverseRoute =
  AuthenticatedNewUniverseRouteImport.update({
    id: '/new-universe',
    path: '/new-universe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUniverseIdRoute = AuthenticatedUniverseIdRouteImport.update({
  id: '/universe/$id',
  path: '/universe/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUniverseIdIndexRoute =
  AuthenticatedUniverseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdChaptersRoute =
  AuthenticatedUniverseIdChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdCharactersRoute =
  AuthenticatedUniverseIdCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdContinuityRoute =
  AuthenticatedUniverseIdContinuityRouteImport.update({
    id: '/continuity',
    path: '/continuity',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdDnaRoute =
  AuthenticatedUniverseIdDnaRouteImport.update({
    id: '/dna',
    path: '/dna',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdMemoryRoute =
  AuthenticatedUniverseIdMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdTimelineRoute =
  AuthenticatedUniverseIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdVersionsRoute =
  AuthenticatedUniverseIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)
const AuthenticatedUniverseIdWorldRoute =
  AuthenticatedUniverseIdWorldRouteImport.update({
    id: '/world',
    path: '/world',
    getParentRoute: () => AuthenticatedUniverseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-universe': typeof AuthenticatedNewUniverseRoute
  '/universe/$id': typeof AuthenticatedUniverseIdRouteWithChildren
  '/universe/$id/chapters': typeof AuthenticatedUniverseIdChaptersRoute
  '/universe/$id/characters': typeof AuthenticatedUniverseIdCharactersRoute
  '/universe/$id/continuity': typeof AuthenticatedUniverseIdContinuityRoute
  '/universe/$id/dna': typeof AuthenticatedUniverseIdDnaRoute
  '/universe/$id/memory': typeof AuthenticatedUniverseIdMemoryRoute
  '/universe/$id/timeline': typeof AuthenticatedUniverseIdTimelineRoute
  '/universe/$id/versions': typeof AuthenticatedUniverseIdVersionsRoute
  '/universe/$id/world': typeof AuthenticatedUniverseIdWorldRoute
  '/universe/$id/': typeof AuthenticatedUniverseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-universe': typeof AuthenticatedNewUniverseRoute
  '/universe/$id/chapters': typeof AuthenticatedUniverseIdChaptersRoute
  '/universe/$id/characters': typeof AuthenticatedUniverseIdCharactersRoute
  '/universe/$id/continuity': typeof AuthenticatedUniverseIdContinuityRoute
  '/universe/$id/dna': typeof AuthenticatedUniverseIdDnaRoute
  '/universe/$id/memory': typeof AuthenticatedUniverseIdMemoryRoute
  '/universe/$id/timeline': typeof AuthenticatedUniverseIdTimelineRoute
  '/universe/$id/versions': typeof AuthenticatedUniverseIdVersionsRoute
  '/universe/$id/world': typeof AuthenticatedUniverseIdWorldRoute
  '/universe/$id': typeof AuthenticatedUniverseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new-universe': typeof AuthenticatedNewUniverseRoute
  '/_authenticated/universe/$id': typeof AuthenticatedUniverseIdRouteWithChildren
  '/_authenticated/universe/$id/chapters': typeof AuthenticatedUniverseIdChaptersRoute
  '/_authenticated/universe/$id/characters': typeof AuthenticatedUniverseIdCharactersRoute
  '/_authenticated/universe/$id/continuity': typeof AuthenticatedUniverseIdContinuityRoute
  '/_authenticated/universe/$id/dna': typeof AuthenticatedUniverseIdDnaRoute
  '/_authenticated/universe/$id/memory': typeof AuthenticatedUniverseIdMemoryRoute
  '/_authenticated/universe/$id/timeline': typeof AuthenticatedUniverseIdTimelineRoute
  '/_authenticated/universe/$id/versions': typeof AuthenticatedUniverseIdVersionsRoute
  '/_authenticated/universe/$id/world': typeof AuthenticatedUniverseIdWorldRoute
  '/_authenticated/universe/$id/': typeof AuthenticatedUniverseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new-universe'
    | '/universe/$id'
    | '/universe/$id/chapters'
    | '/universe/$id/characters'
    | '/universe/$id/continuity'
    | '/universe/$id/dna'
    | '/universe/$id/memory'
    | '/universe/$id/timeline'
    | '/universe/$id/versions'
    | '/universe/$id/world'
    | '/universe/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new-universe'
    | '/universe/$id/chapters'
    | '/universe/$id/characters'
    | '/universe/$id/continuity'
    | '/universe/$id/dna'
    | '/universe/$id/memory'
    | '/universe/$id/timeline'
    | '/universe/$id/versions'
    | '/universe/$id/world'
    | '/universe/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/new-universe'
    | '/_authenticated/universe/$id'
    | '/_authenticated/universe/$id/chapters'
    | '/_authenticated/universe/$id/characters'
    | '/_authenticated/universe/$id/continuity'
    | '/_authenticated/universe/$id/dna'
    | '/_authenticated/universe/$id/memory'
    | '/_authenticated/universe/$id/timeline'
    | '/_authenticated/universe/$id/versions'
    | '/_authenticated/universe/$id/world'
    | '/_authenticated/universe/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-universe': {
      id: '/_authenticated/new-universe'
      path: '/new-universe'
      fullPath: '/new-universe'
      preLoaderRoute: typeof AuthenticatedNewUniverseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/universe/$id': {
      id: '/_authenticated/universe/$id'
      path: '/universe/$id'
      fullPath: '/universe/$id'
      preLoaderRoute: typeof AuthenticatedUniverseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/universe/$id/': {
      id: '/_authenticated/universe/$id/'
      path: '/'
      fullPath: '/universe/$id/'
      preLoaderRoute: typeof AuthenticatedUniverseIdIndexRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/chapters': {
      id: '/_authenticated/universe/$id/chapters'
      path: '/chapters'
      fullPath: '/universe/$id/chapters'
      preLoaderRoute: typeof AuthenticatedUniverseIdChaptersRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/characters': {
      id: '/_authenticated/universe/$id/characters'
      path: '/characters'
      fullPath: '/universe/$id/characters'
      preLoaderRoute: typeof AuthenticatedUniverseIdCharactersRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/continuity': {
      id: '/_authenticated/universe/$id/continuity'
      path: '/continuity'
      fullPath: '/universe/$id/continuity'
      preLoaderRoute: typeof AuthenticatedUniverseIdContinuityRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/dna': {
      id: '/_authenticated/universe/$id/dna'
      path: '/dna'
      fullPath: '/universe/$id/dna'
      preLoaderRoute: typeof AuthenticatedUniverseIdDnaRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/memory': {
      id: '/_authenticated/universe/$id/memory'
      path: '/memory'
      fullPath: '/universe/$id/memory'
      preLoaderRoute: typeof AuthenticatedUniverseIdMemoryRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/timeline': {
      id: '/_authenticated/universe/$id/timeline'
      path: '/timeline'
      fullPath: '/universe/$id/timeline'
      preLoaderRoute: typeof AuthenticatedUniverseIdTimelineRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/versions': {
      id: '/_authenticated/universe/$id/versions'
      path: '/versions'
      fullPath: '/universe/$id/versions'
      preLoaderRoute: typeof AuthenticatedUniverseIdVersionsRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
    '/_authenticated/universe/$id/world': {
      id: '/_authenticated/universe/$id/world'
      path: '/world'
      fullPath: '/universe/$id/world'
      preLoaderRoute: typeof AuthenticatedUniverseIdWorldRouteImport
      parentRoute: typeof AuthenticatedUniverseIdRoute
    }
  }
}

interface AuthenticatedUniverseIdRouteChildren {
  AuthenticatedUniverseIdChaptersRoute: typeof AuthenticatedUniverseIdChaptersRoute
  AuthenticatedUniverseIdCharactersRoute: typeof AuthenticatedUniverseIdCharactersRoute
  AuthenticatedUniverseIdContinuityRoute: typeof AuthenticatedUniverseIdContinuityRoute
  AuthenticatedUniverseIdDnaRoute: typeof AuthenticatedUniverseIdDnaRoute
  AuthenticatedUniverseIdMemoryRoute: typeof AuthenticatedUniverseIdMemoryRoute
  AuthenticatedUniverseIdTimelineRoute: typeof AuthenticatedUniverseIdTimelineRoute
  AuthenticatedUniverseIdVersionsRoute: typeof AuthenticatedUniverseIdVersionsRoute
  AuthenticatedUniverseIdWorldRoute: typeof AuthenticatedUniverseIdWorldRoute
  AuthenticatedUniverseIdIndexRoute: typeof AuthenticatedUniverseIdIndexRoute
}

const AuthenticatedUniverseIdRouteChildren: AuthenticatedUniverseIdRouteChildren =
  {
    AuthenticatedUniverseIdChaptersRoute: AuthenticatedUniverseIdChaptersRoute,
    AuthenticatedUniverseIdCharactersRoute:
      AuthenticatedUniverseIdCharactersRoute,
    AuthenticatedUniverseIdContinuityRoute:
      AuthenticatedUniverseIdContinuityRoute,
    AuthenticatedUniverseIdDnaRoute: AuthenticatedUniverseIdDnaRoute,
    AuthenticatedUniverseIdMemoryRoute: AuthenticatedUniverseIdMemoryRoute,
    AuthenticatedUniverseIdTimelineRoute: AuthenticatedUniverseIdTimelineRoute,
    AuthenticatedUniverseIdVersionsRoute: AuthenticatedUniverseIdVersionsRoute,
    AuthenticatedUniverseIdWorldRoute: AuthenticatedUniverseIdWorldRoute,
    AuthenticatedUniverseIdIndexRoute: AuthenticatedUniverseIdIndexRoute,
  }

const AuthenticatedUniverseIdRouteWithChildren =
  AuthenticatedUniverseIdRoute._addFileChildren(
    AuthenticatedUniverseIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewUniverseRoute: typeof AuthenticatedNewUniverseRoute
  AuthenticatedUniverseIdRoute: typeof AuthenticatedUniverseIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewUniverseRoute: AuthenticatedNewUniverseRoute,
  AuthenticatedUniverseIdRoute: AuthenticatedUniverseIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
